{% set name = "pdm-pep517" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-pep517-{{ version }}.tar.gz
  sha256: d4fa735a645f7e95a6beb34a2b5f7e8e00d93dd0439d73f31cc82e40b5b8fdce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pdm.pep517
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm-pep517/
  summary: A PEP 517 backend for PDM that supports PEP 621 metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
