context:
  name: pdm-pep517
  version: 1.1.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pdm-pep517-${{ version }}.tar.gz
  sha256: 7f49121e70b42dca296fac962210dd2da07a39575fc5673137ad661633b2cf3f

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - pdm-backend
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pdm.pep517
      python_version: ${{ python_min }}.*

about:
  summary: A PEP 517 backend for PDM that supports PEP 621 metadata
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/pdm-pep517/

extra:
  recipe-maintainers:
    - hadim
